swagger: "2.0"
info:
  title: Artist per E-Mail abrufen
  version: "1.0"
  description: Liefert einen Artist-Datensatz anhand der E-Mail (nur für Authentifizierte).
tags:
  - Artists
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
paths:
  /artists/email/{email}:
    get:
      tags: [Artists]
      security: [{ bearerAuth: [] }]
      summary: Artist per E-Mail
      parameters:
        - name: email
          in: path
          required: true
          type: string
          example: "jane@pepeshows.de"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id: { type: integer, example: 12 }
              name: { type: string }
              email: { type: string }
              disciplines:
                type: array
                items: { type: string }
              # ... ggf. weitere Felder aus serialize()
        404:
          description: Artist not found