"""guidedlines accepted for artists in db

Revision ID: 32c83dfc95c5
Revises: a2abe8c15cf5
Create Date: 2025-08-30 11:40:49.027726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c83dfc95c5'
down_revision = 'a2abe8c15cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_disciplines_artist_id_fkey_cascade', 'artist_disciplines', type_='foreignkey')
    op.create_foreign_key('fk_artist_disciplines_artist_id', 'artist_disciplines', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    op.add_column('artists', sa.Column('guidelines_accepted', sa.Boolean(), server_default='false', nullable=False))

    # Rebuild availabilities FKs and keep unique constraint
    op.drop_constraint('availability_unique_artist_date', 'availabilities', type_='unique')
    op.drop_constraint('availabilities_artist_id_fkey_cascade', 'availabilities', type_='foreignkey')
    op.create_foreign_key('fk_availabilities_artist_id', 'availabilities', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('availability_unique_artist_date', 'availabilities', ['artist_id', 'date'])

    op.drop_constraint('booking_artists_artist_id_fkey', 'booking_artists', type_='foreignkey')
    op.create_foreign_key('fk_booking_artists_artist_id', 'booking_artists', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('invoices_artist_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key('fk_invoices_artist_id', 'invoices', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # Drop the named FKs we added
    op.drop_constraint('fk_invoices_artist_id', 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_artist_id_fkey', 'invoices', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('fk_booking_artists_artist_id', 'booking_artists', type_='foreignkey')
    op.create_foreign_key('booking_artists_artist_id_fkey', 'booking_artists', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('fk_availabilities_artist_id', 'availabilities', type_='foreignkey')
    op.create_foreign_key('availabilities_artist_id_fkey_cascade', 'availabilities', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    # restore unique constraint (if Alembic downgrades past this point)
    op.create_unique_constraint('availability_unique_artist_date', 'availabilities', ['artist_id', 'date'])

    op.drop_constraint('fk_artist_disciplines_artist_id', 'artist_disciplines', type_='foreignkey')
    op.create_foreign_key('artist_disciplines_artist_id_fkey_cascade', 'artist_disciplines', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')

    op.drop_column('artists', 'guidelines_accepted')
