"""Apply model length adjustments

Revision ID: 3942986f1707
Revises: 675e540a6bb8
Create Date: 2025-08-04 10:55:06.147672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3942986f1707'
down_revision = '675e540a6bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
