"""Add unique constraint artist_id+date to availability

Revision ID: aa1c94dbeb69
Revises: 5318f0092b8e
Create Date: 2025-08-01 10:04:22.403723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1c94dbeb69'
down_revision = '5318f0092b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_artist_date', ['artist_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_artist_date', type_='unique')

    op.create_table('profiles',
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('phone_number', sa.TEXT(), nullable=True),
    sa.Column('disciplines', sa.TEXT(), nullable=True),
    sa.Column('price_min', sa.INTEGER(), nullable=True),
    sa.Column('price_max', sa.INTEGER(), nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), nullable=True),
    sa.Column('backend_artist_id', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('backend_artist_id', name=op.f('uq_profiles_backend_artist_id'))
    )
    # ### end Alembic commands ###
